### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by mafiavc** [lucaazalim/minecraft-server-ping#10]
how to solve this error? 

`java.lang.NoSuchMethodError: com.sun.jna.Native.load(Ljava/lang/String;Ljava/lang/Class;Ljava/util/Map;)Lcom/sun/jna/Library;
	at org.xbill.DNS.config.IPHlpAPI.<clinit>(IPHlpAPI.java:17)
	at org.xbill.DNS.config.WindowsResolverConfigProvider$InnerWindowsResolverConfigProvider.initialize(WindowsResolverConfigProvider.java:68)
	at org.xbill.DNS.config.WindowsResolverConfigProvider.initialize(WindowsResolverConfigProvider.java:116)
	at org.xbill.DNS.ResolverConfig.<init>(ResolverConfig.java:109)
	at org.xbill.DNS.ResolverConfig.refresh(ResolverConfig.java:99)
	at org.xbill.DNS.ResolverConfig.checkInitialized(ResolverConfig.java:72)
	at org.xbill.DNS.ResolverConfig.getCurrentConfig(ResolverConfig.java:78)
	at org.xbill.DNS.ExtendedResolver.<init>(ExtendedResolver.java:173)
	at org.xbill.DNS.Lookup.refreshDefault(Lookup.java:97)
	at org.xbill.DNS.Lookup.<clinit>(Lookup.java:105)
	at br.com.azalim.mcserverping.MCPing.getPing(MCPing.java:81)`

**Comment by mafiavc** [comment]
this error happened when I add it as a library to my Minecraft client 1.8
